// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAihuzzdQ9rIOJdXO2Z7bf6b2nhWd1ZbMM',
    appId: '1:515530670215:web:5ed47fe17c8818525ab822',
    messagingSenderId: '515530670215',
    projectId: 'true-eye-375516',
    authDomain: 'true-eye-375516.firebaseapp.com',
    storageBucket: 'true-eye-375516.appspot.com',
    measurementId: 'G-JW8D8RNH6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSodY9YZA0u62tJNXblVrMLdUbNwJQee8',
    appId: '1:515530670215:android:1ce0753c7cfbfc7f5ab822',
    messagingSenderId: '515530670215',
    projectId: 'true-eye-375516',
    storageBucket: 'true-eye-375516.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRMMW9zyndWO1RADSfzWowIk-cBOhGUOQ',
    appId: '1:515530670215:ios:48d499fde8f17e845ab822',
    messagingSenderId: '515530670215',
    projectId: 'true-eye-375516',
    storageBucket: 'true-eye-375516.appspot.com',
    iosBundleId: 'com.example.example30May24',
  );
}
